---
# tasks file for containers

- name: Add unsecure Registry 
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restart docker
  shell: systemctl restart docker
  tags: restart

- name: install docker-compose
  shell: apt install docker-compose -y

- name: Create netdata dir
  file:
    path: /srv/netdata
    state: directory

- name: Deploy Compose template
  template:
    src: docker-compose-netdata.j2
    dest: /srv/netdata/docker-compose.yml

- name: Docker Compose up
  shell: "cd /srv/netdata && docker-compose up -d" 
