---
# tasks file for containers

- name: Update & upgrade Sys
  shell: apt-get update -y && apt-get upgrade -y

- name: Install Curl
  apt:
    name: curl
    state: present

- name: curl gpg key
  shell: curl https://haproxy.debian.net/bernat.debian.org.gpg | apt-key add -

- name: add HaProxy repo to apt
  shell: echo "deb http://haproxy.debian.net $(lsb_release -cs)-backports-2.0 main" | tee /etc/apt/sources.list.d/haproxy.list

- name: install HaProxy 
  apt:
    name: haproxy
    state: present

- name: Add new haproxy config file
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

- name: restart haproxy
  shell: systemctl restart haproxy
