---
# tasks file for docker

- name: Ensure necessary packages exists
  import_tasks: packages.yml

- name: Install Docker
  import_tasks: install_docker.yml

- name: Install Swarm for a standalone
  import_tasks: install_standalone_swarm.yml
  when: inventory_hostname in groups['standalone']
  tags: swarm-stand
