---
- name: Update the apt package index
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Ensure necessary packages are present
  apt:
    name: "{{ item.name }}={{ item.version }}"
    update_cache: true
    force_apt_get: true
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ packages }}"
